### ISSUE TITLE
FR: Forward message

### ISSUE THREAD

**Issue by agenbite** [akissinger/dodo#1]
Congrats on this interesting software which might indeed fill a gap. I gave it a try and missed the forwarding messages functionality. It'd be nice to have the possibility to forward an html-only message as a plain text message, something that I've found difficult in notmuch-emacs.

Keep it up!!

**Comment by akissinger** [comment]
Yes, that's actually next in my TODO.

I think the only non-trivial bit of work here is figuring out what to do about attachments. For transparency, I'd like to keep the whole state of the message in "compose" mode in plain text. E.g. attachments are just pseudo-headers "A:"

A couple of options I've thought of are:

1. just dumping out the attachments to a temp dir and adding "A: ..." to the draft message for each one. I guess this temp dir can be cleaned up as soon as the compose tab is closed.
2. adding a new pseudo-header like "Forward-Attachments-From:" which takes a message ID. When you send a message, it should use notmuch to locate the message by ID, pull out the attachments, and attach them to the new message.

Certainly option 1 is simpler, I'm just trying to think of a case where this might behave strangely. Possibly if I ever implement features for saving drafts and coming back to them later...

**Comment by agenbite** [comment]
I agree that option 2 might be more robust.
