### ISSUE TITLE
Configuring panel layout

### ISSUE THREAD

**Issue by aecepogluARUP** [akissinger/dodo#13]
Is the panel layout easily configurable? I'd like to change the ThreadView panel sizes and positions

**Comment by akissinger** [comment]
In the latest version, you can customise the layout of `ThreadPanel` by swapping in your own `layout_panel` method in `config.py`. It's a bit verbose, but this seems simpler and more flexible than introducing a handful of settings for this.

This is now documented [here](https://github.com/akissinger/dodo#custom-layouts).

**Comment by aecepogluARUP** [comment]
its verbosity is perfectly fine. I  just wanted an option that didn't require me to rebuild the program each time I configured something. This may do just that.

Thanks.
