### ISSUE TITLE
Configuring vim in xfce4-terminal as editor

### ISSUE THREAD

**Issue by agenbite** [akissinger/dodo#3]
Depending on the terminal specification, the current definition scheme for the editor can fail. I'm trying to use the following in my config file:

```
dodo.settings.editor_command = ["xfce4-terminal", "--disable-server", "--geometry", "86x24+40+60", "-e", "vim"]
```

and I get an error `xfce4-terminal: Unknown option "/tmp/tmp9ztrlszu.eml"`. In qutebrowser, for example, I can add `{file}` after `"vim"` and thus the call works.

**Comment by agenbite** [comment]
The solution was to replace `-e` by `-x`, which executes the rest of the line inside the terminal. Sorry for the noise.

**Comment by akissinger** [comment]
Giving custom commands as a shell command with a placeholder for file/folder/etc might still be better than an array of args, which is quite limited.

**Comment by akissinger** [comment]
I've implemented this now. See https://github.com/akissinger/dodo#configuration for how to update your `config.py` to the new style.
