### ISSUE TITLE
Define custom bindings in config file

### ISSUE THREAD

**Issue by agenbite** [akissinger/dodo#5]
It is somehow inconvenient to customize key bindings in the source code tree, since any `git pull` will complain of conflicting changes and force the user to stash/merge. Wouldn't it be nicer to edit the bindings directly in the `config.py` file? I tried to copy the mapping dictionaries into that file and it doesn't seem to work.

(Sorry for too many feature requests and too few PRs, but python is not my mother tongue... Thanks again for this software!!)

**Comment by akissinger** [comment]
It's intended that you do this from `config.py` already, but this wasn't explained very well in the README. I've expanded on this now: https://github.com/akissinger/dodo#key-mapping
