### ISSUE TITLE
Problem with mbsync

### ISSUE THREAD

**Issue by agenbite** [akissinger/dodo#6]
I've set `dodo.settings.sync_mail_command = 'mbsync my-mail-box'` and I'm getting this error at regular intervals:
```
FileNotFoundError: [Errno 2] No such file or directory: 'mbsync my-mail-box'
```
However, I have a system service for fetching mail through IMAP IDLE and I don't need Dodo to take care of fetching mail. Thus, I've set `sync_mail_command` to `''` and the error is now
```
PermissionError: [Errno 13] Permission denied: ''
```

**Comment by akissinger** [comment]
try `dodo.settings.sync_mail_command = ['mbsync', 'my-mail-box']`.

To disable automatic sync, set `dodo.settings.sync_mail_interval = -1`

**Comment by agenbite** [comment]
Cool. Both work. :)
